// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Layout from "@/Components/layOut";
import { LogoProvider } from '@/Components/LogoContext';
import ThemeProviderWrapper from "@/Components/ThemeProviderWrapper";
import BottomDialogButton from "@/Components/BottomDialogButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CREMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProviderWrapper>
          <LogoProvider>
            <Layout>
              {children}
            </Layout>
            <BottomDialogButton />
          </LogoProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}